# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywishlist',
            name='owner',
            field=models.CharField(default='', max_length=45),
        ),
    ]
