# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_auto_20170329_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywishlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mywishlist', to='login_and_reg_app.User'),
        ),
    ]
